on: [push, pull_request]

jobs:
  Quality-Checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir:
          - hack/test-all-tasks
          - pipelines
          - tasks
    steps:
      - name: checkout
        uses: actions/checkout@v2 
      - name: Install oc
        uses: redhat-actions/oc-installer@v1
        with:
          oc_version: '4.6'
      - name: Install kubeval cli
        uses: sawood14012/setup-kubeval-cli@v1.1
        with:
          version: '0.16.1'
      - name: ${{ matrix.dir }}-yaml-validation
        uses: sawood14012/openshift-yaml-validate-action@v1.1
        with:
          files: ${{ matrix.dir }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
